//
//  RequestNetworkModel.swift
//  PlaningHSCT
//
//  Created by Момотов Евгений Олегович on 27.05.2020.
//

import Foundation

struct RequestNetworkModel: Codable {
    let id: Int
    let disease_status: String?
    let diagnosis: String?
    let diagnosis_icd_id: Int?
    let diagnosis_date: String?
    let complications: String?
    let secondary_diagnoses: String?
    let anti_cmv_igg_id: Int?
    let indications: String?
    let indications_date: String?
    let optimal_hsct_date: String?
    let hsct_type_id: Int?
    let has_siblings: Bool?
    let int_pdonors_count: Int?
    let mis_id: Int?
    let patient_id: Int?
    let department_id: Int?
    let doctor_id: Int?
    let representative_id: Int?
    let weight: Int?
    let blood_type_id: Int?
    let clinic_id: Int?
    let created_at: String?
    let updated_at: String?
    let unrelated_donor_search: String?
    let search_start_date: String?
    let search_end_date: String?
    let diagnosis_hsct_id: Int?
    let source: String?
    let hsct_number: Int?
    let intended_hsct_date: String?
    let is_hla_typed: Bool?
    let intended_exact_hsct_date: String?
    let hsct_date: String?
    let hsct_department_id: Int?
    let hsct_clinic_id: Int?
    let int_donors_count: Int?
    let ru_donors_count: Int?
    let ru_pdonors_count: Int?
    let cgm_status_version_id: Int?
    let direct_clinic_id: Int?
    let hsct_detalization_id: Int?
    let hsctdb_status: String?
    let hsctbio_status: String?
    let cartcells_status: String?
    let elispot_status: String?
    let hospitalization_date: String?
    let processing_type_id: Int?
    let tbi_check: Bool?
    let tai_check: Bool?
    let tbi_tai_date: String?
    let height: Int?
    let body_area: Double?
    let identifier: String?
    let his_status: String?
    let is_cart: Bool?
    let relapse_num: String?
    let relapse_localization: String?
    let blinatumomab_count: Int?
    let blast_cells: String?
    let bone_puncture_date: String?
    let cart_infusion_day: String?
    let liquor: String?
    let mrd_by_cyto: String?
    let localization: String?
    let imunn_blast: String?
    let cd19_expression: String?
    let himer_copy_abl: String?
    let translocation: String?
    let himer_copy: String?
    let himer_copy_unit: String?
    let himer_expression: String?
    let hemogram_date: String?
    let wbc: String?
    let neu: String?
    let platelets: String?
    let hemoglobin: String?
    let blood_chemistry_date: String?
    let kreatinin: String?
    let alt: String?
    let direct_bilirubin: String?
    let common_bilirubin: String?
    let ferritin: String?
    let fibrinogen: String?
    let mho: String?
    let hcv: String?
    let hiv: String?
    let hbv: String?
    let chss: String?
    let chdd: String?
    let ad: String?
    let karnky_lanky_index: Int?
    let echokg: String?
    let ejection_fraction_by_echokg: String?
    let echokg_deviation: String?
    let cerebral_symptoms_description: String?
    let focal_symptoms_description: String?
    let pupil_size: String?
    let finger_probe: String?
    let gvhd_stage24_description: String?
    let gvhd_chronic_description: String?
    let tumor_load: String?
    let blinatumomab: String?
    let hsct_allo: String?
    let extramedullar_compt: String?
    let mrd_by_realtime: String?
    let hypocoagulation: String?
    let cerebral_symptoms: String?
    let focal_symptoms: String?
    let g_serum: String?
    let saturation: String?
    let temp: String?
    let glazgo_points: String?
    let nistgam: String?
    let hallucinations: String?
    let cramps: String?
    let neuro_deficit: String?
    let gvhd_chronic_display: String?
    let gvhd_stage24_display: String?
    let pelvic_function: String?
    let patter: String?
    let romberg_pose: String?
    let cmv: String?
    let cgm_donor_type: String?
    let prev_hsct_date: String?
    let status_id: String?
    let status_redirect: String?
    let redirected_to_nil: Bool?
}
